name: WorldLoader
main: Goldish\WorldLoader\WorldLoader
version: 1.0
api: [3.0.0-ALPHA6, 3.0.1]
load: STARTUP
author: Goldish_Kirby
description: "Automatically loads world on server start"

commands:
 loadworlds:
  description: "Loads all worlds"
  usage: "/loadworlds"
  permission: worldloader.command.loadworld
